import resend

from src.config.settings import settings

resend.api_key = settings.resend_api_key


def send_summary(subject: str, content: str) -> None:
    resend.Emails.send({
        "from": settings.resend_from_email,
        "to": settings.resend_to_email,
        "subject": subject,
        "text": content,
        "html": _to_html(subject, content),
    })


def _to_html(title: str, content: str) -> str:
    items = [
        f"<li>{line[1:].strip()}</li>"
        for line in content.splitlines()
        if line.startswith("•")
    ]
    list_html = "<ul>\n" + "\n".join(items) + "\n</ul>" if items else f"<p>{content}</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f5;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

          <!-- Header -->
          <tr>
            <td style="background-color:#18181b;border-radius:12px 12px 0 0;padding:28px 36px;">
              <p style="margin:0;font-size:12px;font-weight:600;letter-spacing:2px;color:#a1a1aa;text-transform:uppercase;">Dobby</p>
              <h1 style="margin:6px 0 0;font-size:22px;font-weight:700;color:#ffffff;">{title.replace("Dobby — ", "")}</h1>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="background-color:#ffffff;padding:32px 36px;">
              <style>
                ul {{ margin: 0; padding: 0; list-style: none; }}
                li {{
                  padding: 12px 0;
                  border-bottom: 1px solid #f4f4f5;
                  font-size: 15px;
                  line-height: 1.6;
                  color: #3f3f46;
                  padding-left: 20px;
                  position: relative;
                }}
                li:last-child {{ border-bottom: none; }}
                li::before {{
                  content: "▸";
                  position: absolute;
                  left: 0;
                  color: #6366f1;
                  font-size: 12px;
                  top: 14px;
                }}
              </style>
              {list_html}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color:#fafafa;border-top:1px solid #e4e4e7;border-radius:0 0 12px 12px;padding:18px 36px;">
              <p style="margin:0;font-size:12px;color:#a1a1aa;">Generated by Dobby · Your personal AI assistant</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""
