apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dobby.fullname" . }}
  labels:
    {{- include "dobby.labels" . | nindent 4 }}
data:
  OPENAI_MODEL: {{ .Values.config.openaiModel | quote }}
  OPENAI_EMBEDDING_MODEL: {{ .Values.config.openaiEmbeddingModel | quote }}
  HOMEASSISTANT_URL: {{ .Values.config.homeassistantUrl | quote }}
  FINANCES_URL: {{ .Values.config.financesUrl | quote }}
  DIET_URL: {{ .Values.config.dietUrl | quote }}
