apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dobby.fullname" . }}
  labels:
    {{- include "dobby.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dobby.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dobby.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL_ALEMBIC
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DATABASE_URL_ALEMBIC
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: { { .Values.existingSecret } }
                  key: DATABASE_URL

      containers:
        - name: dobby
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "dobby.fullname" . }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
