apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dobby.fullname" . }}
  labels:
    {{- include "dobby.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  HOMEASSISTANT_TOKEN: {{ .Values.secrets.homeassistantToken | quote }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  RESEND_FROM_EMAIL: {{ .Values.secrets.resendFromEmail | quote }}
  RESEND_TO_EMAIL: {{ .Values.secrets.resendToEmail | quote }}
